language: python
python:
  - "2.7"

sudo: required

virtualenv:
  system_site_packages: true

install:
  - pip install -r dev-requirements.txt
#  - sudo apt-get install -qq python-pyside --fix-missing

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - coverage run setup.py test

after_success:
  - coveralls
