language: python
python:
  - "2.7"

install: pip install -r requirements.txt

before_script: flake8 .

script:
  - coverage run --source=pynocchio_comic_reader setup.py test

after_success:
  - coveralls